spring:
  application:
    name: lottery_system

participants:
  file:
    path: src/main/resources/participants.json

lottery_events:
  file:
    path: src/main/resources/lottery_events.json

ballots:
  file:
    path: src/main/resources/submitted_ballots.json